from .student import Student
from .faculty import Faculty
from .course import Course
from .course_module import CourseModule
from .student_module_progress import StudentModuleProgress
from .batch import Batch
from .attendance import Attendance
from models.certificate import Certificate
from models.course_application import CourseApplication
from .institute import Institute
from .notification import NotificationLog
from .user import User
from .admin import Admin
from .fees import Fee
from .notice import Notice